apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: app-demo
type: Opaque
stringData:
  DATABASE_URL: "postgres://postgres:Admin123@kubepostgres.postgres.database.azure.com:5432/postgres?sslmode=require"